version: '3'
services:
  www:
    image: php:8.1.1-apache
    environment:
      - "TZ=America/Tijuana"
    volumes:
      - "./app/:/var/www/html"
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 4000:80
    networks:
      - lamp-docker
    command: >
      sh -c "docker-php-ext-install pdo pdo_mysql mysqli && apache2-foreground"
  
networks:
  lamp-docker:
    driver: bridge
